fix: Remove all IconSource attributes causing XAML parse errors
Removed IconSource references to missing /Resources/ image files:
- /Resources/agent-icon.png
- /Resources/chat-icon.png
- /Resources/chart-icon.png
- /Resources/window-icon.png
- /Resources/log-icon.png

Error: 'Provide value on System.Windows.Baml2006.TypeConverterMarkupExtension
threw an exception' at MainWindow.xaml line 93/137, position 52.

Icons can be added later as actual resource files. System now stable.